[build]
  command = "rm -rf _site && npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"
  ELEVENTY_PRODUCTION = "true"
  # Enable Git-based file tracking
  NETLIFY_CMS_GIT_BASED = "true"

# Improved caching headers
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'self'"

# Admin panel needs different headers
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Frame-Options = "SAMEORIGIN"

# 404 redirects
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Important for CMS - enable CORS for admin
[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Preview URLs
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/builders/:splat"
  status = 200

# Enable instant cache invalidation
[[plugins]]
  
  [plugins.inputs]
    paths = [
      "node_modules/.cache/eleventy",
      "src/opportunities"
    ]